apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-min-app-dp
  labels:
    app: otus-min-app-dp
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      env: otus-min-app
  template:
    metadata:
      labels:
        env: otus-min-app
    spec:
      containers:
      - name: otus-min-app
        image: maxmiracle/otus-min-service:3
        ports:
        - containerPort: 8000