apiVersion: v1
kind: Service
metadata:
  name: otus-min-app-svc
spec:
  selector:
    env: otus-min-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8000
  type: ClusterIP